version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: davenicholasandrew
      POSTGRES_PASSWORD: davenicholasandrew
      POSTGRES_DB: davenicholasandrew
    ports:
      - "5432:5432"
